version: '3.8'
services:
  postgredb:
    container_name: kasikorn-line-assignment
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - '5050:5432'
    volumes:
      - pgdata:/var/lib/lib/postgresql/data
volumes:
  pgdata: