// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/accountflags"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/accounts"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/users"
)

// AccountFlagsCreate is the builder for creating a AccountFlags entity.
type AccountFlagsCreate struct {
	config
	mutation *AccountFlagsMutation
	hooks    []Hook
}

// SetAccountID sets the "account_id" field.
func (afc *AccountFlagsCreate) SetAccountID(i int) *AccountFlagsCreate {
	afc.mutation.SetAccountID(i)
	return afc
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (afc *AccountFlagsCreate) SetNillableAccountID(i *int) *AccountFlagsCreate {
	if i != nil {
		afc.SetAccountID(*i)
	}
	return afc
}

// SetUserID sets the "user_id" field.
func (afc *AccountFlagsCreate) SetUserID(i int) *AccountFlagsCreate {
	afc.mutation.SetUserID(i)
	return afc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (afc *AccountFlagsCreate) SetNillableUserID(i *int) *AccountFlagsCreate {
	if i != nil {
		afc.SetUserID(*i)
	}
	return afc
}

// SetFlagType sets the "flag_type" field.
func (afc *AccountFlagsCreate) SetFlagType(s string) *AccountFlagsCreate {
	afc.mutation.SetFlagType(s)
	return afc
}

// SetFlagValue sets the "flag_value" field.
func (afc *AccountFlagsCreate) SetFlagValue(s string) *AccountFlagsCreate {
	afc.mutation.SetFlagValue(s)
	return afc
}

// SetCreatedAt sets the "created_at" field.
func (afc *AccountFlagsCreate) SetCreatedAt(t time.Time) *AccountFlagsCreate {
	afc.mutation.SetCreatedAt(t)
	return afc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (afc *AccountFlagsCreate) SetNillableCreatedAt(t *time.Time) *AccountFlagsCreate {
	if t != nil {
		afc.SetCreatedAt(*t)
	}
	return afc
}

// SetUpdatedAt sets the "updated_at" field.
func (afc *AccountFlagsCreate) SetUpdatedAt(t time.Time) *AccountFlagsCreate {
	afc.mutation.SetUpdatedAt(t)
	return afc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (afc *AccountFlagsCreate) SetNillableUpdatedAt(t *time.Time) *AccountFlagsCreate {
	if t != nil {
		afc.SetUpdatedAt(*t)
	}
	return afc
}

// SetUsersID sets the "users" edge to the Users entity by ID.
func (afc *AccountFlagsCreate) SetUsersID(id int) *AccountFlagsCreate {
	afc.mutation.SetUsersID(id)
	return afc
}

// SetNillableUsersID sets the "users" edge to the Users entity by ID if the given value is not nil.
func (afc *AccountFlagsCreate) SetNillableUsersID(id *int) *AccountFlagsCreate {
	if id != nil {
		afc = afc.SetUsersID(*id)
	}
	return afc
}

// SetUsers sets the "users" edge to the Users entity.
func (afc *AccountFlagsCreate) SetUsers(u *Users) *AccountFlagsCreate {
	return afc.SetUsersID(u.ID)
}

// SetAccountsID sets the "accounts" edge to the Accounts entity by ID.
func (afc *AccountFlagsCreate) SetAccountsID(id int) *AccountFlagsCreate {
	afc.mutation.SetAccountsID(id)
	return afc
}

// SetNillableAccountsID sets the "accounts" edge to the Accounts entity by ID if the given value is not nil.
func (afc *AccountFlagsCreate) SetNillableAccountsID(id *int) *AccountFlagsCreate {
	if id != nil {
		afc = afc.SetAccountsID(*id)
	}
	return afc
}

// SetAccounts sets the "accounts" edge to the Accounts entity.
func (afc *AccountFlagsCreate) SetAccounts(a *Accounts) *AccountFlagsCreate {
	return afc.SetAccountsID(a.ID)
}

// Mutation returns the AccountFlagsMutation object of the builder.
func (afc *AccountFlagsCreate) Mutation() *AccountFlagsMutation {
	return afc.mutation
}

// Save creates the AccountFlags in the database.
func (afc *AccountFlagsCreate) Save(ctx context.Context) (*AccountFlags, error) {
	afc.defaults()
	return withHooks(ctx, afc.sqlSave, afc.mutation, afc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (afc *AccountFlagsCreate) SaveX(ctx context.Context) *AccountFlags {
	v, err := afc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (afc *AccountFlagsCreate) Exec(ctx context.Context) error {
	_, err := afc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (afc *AccountFlagsCreate) ExecX(ctx context.Context) {
	if err := afc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (afc *AccountFlagsCreate) defaults() {
	if _, ok := afc.mutation.CreatedAt(); !ok {
		v := accountflags.DefaultCreatedAt()
		afc.mutation.SetCreatedAt(v)
	}
	if _, ok := afc.mutation.UpdatedAt(); !ok {
		v := accountflags.DefaultUpdatedAt()
		afc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (afc *AccountFlagsCreate) check() error {
	if _, ok := afc.mutation.FlagType(); !ok {
		return &ValidationError{Name: "flag_type", err: errors.New(`ent: missing required field "AccountFlags.flag_type"`)}
	}
	if _, ok := afc.mutation.FlagValue(); !ok {
		return &ValidationError{Name: "flag_value", err: errors.New(`ent: missing required field "AccountFlags.flag_value"`)}
	}
	if _, ok := afc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountFlags.created_at"`)}
	}
	if _, ok := afc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountFlags.updated_at"`)}
	}
	return nil
}

func (afc *AccountFlagsCreate) sqlSave(ctx context.Context) (*AccountFlags, error) {
	if err := afc.check(); err != nil {
		return nil, err
	}
	_node, _spec := afc.createSpec()
	if err := sqlgraph.CreateNode(ctx, afc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	afc.mutation.id = &_node.ID
	afc.mutation.done = true
	return _node, nil
}

func (afc *AccountFlagsCreate) createSpec() (*AccountFlags, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountFlags{config: afc.config}
		_spec = sqlgraph.NewCreateSpec(accountflags.Table, sqlgraph.NewFieldSpec(accountflags.FieldID, field.TypeInt))
	)
	if value, ok := afc.mutation.FlagType(); ok {
		_spec.SetField(accountflags.FieldFlagType, field.TypeString, value)
		_node.FlagType = value
	}
	if value, ok := afc.mutation.FlagValue(); ok {
		_spec.SetField(accountflags.FieldFlagValue, field.TypeString, value)
		_node.FlagValue = value
	}
	if value, ok := afc.mutation.CreatedAt(); ok {
		_spec.SetField(accountflags.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := afc.mutation.UpdatedAt(); ok {
		_spec.SetField(accountflags.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := afc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountflags.UsersTable,
			Columns: []string{accountflags.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := afc.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountflags.AccountsTable,
			Columns: []string{accountflags.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accounts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccountFlagsCreateBulk is the builder for creating many AccountFlags entities in bulk.
type AccountFlagsCreateBulk struct {
	config
	err      error
	builders []*AccountFlagsCreate
}

// Save creates the AccountFlags entities in the database.
func (afcb *AccountFlagsCreateBulk) Save(ctx context.Context) ([]*AccountFlags, error) {
	if afcb.err != nil {
		return nil, afcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(afcb.builders))
	nodes := make([]*AccountFlags, len(afcb.builders))
	mutators := make([]Mutator, len(afcb.builders))
	for i := range afcb.builders {
		func(i int, root context.Context) {
			builder := afcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountFlagsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, afcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, afcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, afcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (afcb *AccountFlagsCreateBulk) SaveX(ctx context.Context) []*AccountFlags {
	v, err := afcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (afcb *AccountFlagsCreateBulk) Exec(ctx context.Context) error {
	_, err := afcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (afcb *AccountFlagsCreateBulk) ExecX(ctx context.Context) {
	if err := afcb.Exec(ctx); err != nil {
		panic(err)
	}
}
