// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/accountbalances"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/accounts"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/users"
)

// AccountBalances is the model entity for the AccountBalances schema.
type AccountBalances struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int `json:"account_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountBalancesQuery when eager-loading is set.
	Edges        AccountBalancesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountBalancesEdges holds the relations/edges for other nodes in the graph.
type AccountBalancesEdges struct {
	// Users holds the value of the users edge.
	Users *Users `json:"users,omitempty"`
	// Accounts holds the value of the accounts edge.
	Accounts *Accounts `json:"accounts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountBalancesEdges) UsersOrErr() (*Users, error) {
	if e.Users != nil {
		return e.Users, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: users.Label}
	}
	return nil, &NotLoadedError{edge: "users"}
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountBalancesEdges) AccountsOrErr() (*Accounts, error) {
	if e.Accounts != nil {
		return e.Accounts, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: accounts.Label}
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountBalances) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountbalances.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case accountbalances.FieldID, accountbalances.FieldAccountID, accountbalances.FieldUserID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountBalances fields.
func (ab *AccountBalances) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountbalances.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ab.ID = int(value.Int64)
		case accountbalances.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				ab.AccountID = int(value.Int64)
			}
		case accountbalances.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ab.UserID = int(value.Int64)
			}
		case accountbalances.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				ab.Amount = value.Float64
			}
		default:
			ab.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountBalances.
// This includes values selected through modifiers, order, etc.
func (ab *AccountBalances) Value(name string) (ent.Value, error) {
	return ab.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the AccountBalances entity.
func (ab *AccountBalances) QueryUsers() *UsersQuery {
	return NewAccountBalancesClient(ab.config).QueryUsers(ab)
}

// QueryAccounts queries the "accounts" edge of the AccountBalances entity.
func (ab *AccountBalances) QueryAccounts() *AccountsQuery {
	return NewAccountBalancesClient(ab.config).QueryAccounts(ab)
}

// Update returns a builder for updating this AccountBalances.
// Note that you need to call AccountBalances.Unwrap() before calling this method if this AccountBalances
// was returned from a transaction, and the transaction was committed or rolled back.
func (ab *AccountBalances) Update() *AccountBalancesUpdateOne {
	return NewAccountBalancesClient(ab.config).UpdateOne(ab)
}

// Unwrap unwraps the AccountBalances entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ab *AccountBalances) Unwrap() *AccountBalances {
	_tx, ok := ab.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountBalances is not a transactional entity")
	}
	ab.config.driver = _tx.drv
	return ab
}

// String implements the fmt.Stringer.
func (ab *AccountBalances) String() string {
	var builder strings.Builder
	builder.WriteString("AccountBalances(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ab.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", ab.AccountID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ab.UserID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", ab.Amount))
	builder.WriteByte(')')
	return builder.String()
}

// AccountBalancesSlice is a parsable slice of AccountBalances.
type AccountBalancesSlice []*AccountBalances
