// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/debitcarddetails"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/debitcards"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/predicate"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/users"
)

// DebitCardDetailsUpdate is the builder for updating DebitCardDetails entities.
type DebitCardDetailsUpdate struct {
	config
	hooks    []Hook
	mutation *DebitCardDetailsMutation
}

// Where appends a list predicates to the DebitCardDetailsUpdate builder.
func (dcdu *DebitCardDetailsUpdate) Where(ps ...predicate.DebitCardDetails) *DebitCardDetailsUpdate {
	dcdu.mutation.Where(ps...)
	return dcdu
}

// SetCardID sets the "card_id" field.
func (dcdu *DebitCardDetailsUpdate) SetCardID(i int) *DebitCardDetailsUpdate {
	dcdu.mutation.SetCardID(i)
	return dcdu
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (dcdu *DebitCardDetailsUpdate) SetNillableCardID(i *int) *DebitCardDetailsUpdate {
	if i != nil {
		dcdu.SetCardID(*i)
	}
	return dcdu
}

// ClearCardID clears the value of the "card_id" field.
func (dcdu *DebitCardDetailsUpdate) ClearCardID() *DebitCardDetailsUpdate {
	dcdu.mutation.ClearCardID()
	return dcdu
}

// SetUserID sets the "user_id" field.
func (dcdu *DebitCardDetailsUpdate) SetUserID(i int) *DebitCardDetailsUpdate {
	dcdu.mutation.SetUserID(i)
	return dcdu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (dcdu *DebitCardDetailsUpdate) SetNillableUserID(i *int) *DebitCardDetailsUpdate {
	if i != nil {
		dcdu.SetUserID(*i)
	}
	return dcdu
}

// ClearUserID clears the value of the "user_id" field.
func (dcdu *DebitCardDetailsUpdate) ClearUserID() *DebitCardDetailsUpdate {
	dcdu.mutation.ClearUserID()
	return dcdu
}

// SetIssuer sets the "issuer" field.
func (dcdu *DebitCardDetailsUpdate) SetIssuer(s string) *DebitCardDetailsUpdate {
	dcdu.mutation.SetIssuer(s)
	return dcdu
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (dcdu *DebitCardDetailsUpdate) SetNillableIssuer(s *string) *DebitCardDetailsUpdate {
	if s != nil {
		dcdu.SetIssuer(*s)
	}
	return dcdu
}

// SetNumber sets the "number" field.
func (dcdu *DebitCardDetailsUpdate) SetNumber(s string) *DebitCardDetailsUpdate {
	dcdu.mutation.SetNumber(s)
	return dcdu
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (dcdu *DebitCardDetailsUpdate) SetNillableNumber(s *string) *DebitCardDetailsUpdate {
	if s != nil {
		dcdu.SetNumber(*s)
	}
	return dcdu
}

// SetUsersID sets the "users" edge to the Users entity by ID.
func (dcdu *DebitCardDetailsUpdate) SetUsersID(id int) *DebitCardDetailsUpdate {
	dcdu.mutation.SetUsersID(id)
	return dcdu
}

// SetNillableUsersID sets the "users" edge to the Users entity by ID if the given value is not nil.
func (dcdu *DebitCardDetailsUpdate) SetNillableUsersID(id *int) *DebitCardDetailsUpdate {
	if id != nil {
		dcdu = dcdu.SetUsersID(*id)
	}
	return dcdu
}

// SetUsers sets the "users" edge to the Users entity.
func (dcdu *DebitCardDetailsUpdate) SetUsers(u *Users) *DebitCardDetailsUpdate {
	return dcdu.SetUsersID(u.ID)
}

// SetDebitCardsID sets the "debit_cards" edge to the DebitCards entity by ID.
func (dcdu *DebitCardDetailsUpdate) SetDebitCardsID(id int) *DebitCardDetailsUpdate {
	dcdu.mutation.SetDebitCardsID(id)
	return dcdu
}

// SetNillableDebitCardsID sets the "debit_cards" edge to the DebitCards entity by ID if the given value is not nil.
func (dcdu *DebitCardDetailsUpdate) SetNillableDebitCardsID(id *int) *DebitCardDetailsUpdate {
	if id != nil {
		dcdu = dcdu.SetDebitCardsID(*id)
	}
	return dcdu
}

// SetDebitCards sets the "debit_cards" edge to the DebitCards entity.
func (dcdu *DebitCardDetailsUpdate) SetDebitCards(d *DebitCards) *DebitCardDetailsUpdate {
	return dcdu.SetDebitCardsID(d.ID)
}

// Mutation returns the DebitCardDetailsMutation object of the builder.
func (dcdu *DebitCardDetailsUpdate) Mutation() *DebitCardDetailsMutation {
	return dcdu.mutation
}

// ClearUsers clears the "users" edge to the Users entity.
func (dcdu *DebitCardDetailsUpdate) ClearUsers() *DebitCardDetailsUpdate {
	dcdu.mutation.ClearUsers()
	return dcdu
}

// ClearDebitCards clears the "debit_cards" edge to the DebitCards entity.
func (dcdu *DebitCardDetailsUpdate) ClearDebitCards() *DebitCardDetailsUpdate {
	dcdu.mutation.ClearDebitCards()
	return dcdu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dcdu *DebitCardDetailsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, dcdu.sqlSave, dcdu.mutation, dcdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dcdu *DebitCardDetailsUpdate) SaveX(ctx context.Context) int {
	affected, err := dcdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dcdu *DebitCardDetailsUpdate) Exec(ctx context.Context) error {
	_, err := dcdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcdu *DebitCardDetailsUpdate) ExecX(ctx context.Context) {
	if err := dcdu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (dcdu *DebitCardDetailsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(debitcarddetails.Table, debitcarddetails.Columns, sqlgraph.NewFieldSpec(debitcarddetails.FieldID, field.TypeInt))
	if ps := dcdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dcdu.mutation.Issuer(); ok {
		_spec.SetField(debitcarddetails.FieldIssuer, field.TypeString, value)
	}
	if value, ok := dcdu.mutation.Number(); ok {
		_spec.SetField(debitcarddetails.FieldNumber, field.TypeString, value)
	}
	if dcdu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   debitcarddetails.UsersTable,
			Columns: []string{debitcarddetails.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dcdu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   debitcarddetails.UsersTable,
			Columns: []string{debitcarddetails.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dcdu.mutation.DebitCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   debitcarddetails.DebitCardsTable,
			Columns: []string{debitcarddetails.DebitCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(debitcards.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dcdu.mutation.DebitCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   debitcarddetails.DebitCardsTable,
			Columns: []string{debitcarddetails.DebitCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(debitcards.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dcdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{debitcarddetails.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dcdu.mutation.done = true
	return n, nil
}

// DebitCardDetailsUpdateOne is the builder for updating a single DebitCardDetails entity.
type DebitCardDetailsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DebitCardDetailsMutation
}

// SetCardID sets the "card_id" field.
func (dcduo *DebitCardDetailsUpdateOne) SetCardID(i int) *DebitCardDetailsUpdateOne {
	dcduo.mutation.SetCardID(i)
	return dcduo
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (dcduo *DebitCardDetailsUpdateOne) SetNillableCardID(i *int) *DebitCardDetailsUpdateOne {
	if i != nil {
		dcduo.SetCardID(*i)
	}
	return dcduo
}

// ClearCardID clears the value of the "card_id" field.
func (dcduo *DebitCardDetailsUpdateOne) ClearCardID() *DebitCardDetailsUpdateOne {
	dcduo.mutation.ClearCardID()
	return dcduo
}

// SetUserID sets the "user_id" field.
func (dcduo *DebitCardDetailsUpdateOne) SetUserID(i int) *DebitCardDetailsUpdateOne {
	dcduo.mutation.SetUserID(i)
	return dcduo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (dcduo *DebitCardDetailsUpdateOne) SetNillableUserID(i *int) *DebitCardDetailsUpdateOne {
	if i != nil {
		dcduo.SetUserID(*i)
	}
	return dcduo
}

// ClearUserID clears the value of the "user_id" field.
func (dcduo *DebitCardDetailsUpdateOne) ClearUserID() *DebitCardDetailsUpdateOne {
	dcduo.mutation.ClearUserID()
	return dcduo
}

// SetIssuer sets the "issuer" field.
func (dcduo *DebitCardDetailsUpdateOne) SetIssuer(s string) *DebitCardDetailsUpdateOne {
	dcduo.mutation.SetIssuer(s)
	return dcduo
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (dcduo *DebitCardDetailsUpdateOne) SetNillableIssuer(s *string) *DebitCardDetailsUpdateOne {
	if s != nil {
		dcduo.SetIssuer(*s)
	}
	return dcduo
}

// SetNumber sets the "number" field.
func (dcduo *DebitCardDetailsUpdateOne) SetNumber(s string) *DebitCardDetailsUpdateOne {
	dcduo.mutation.SetNumber(s)
	return dcduo
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (dcduo *DebitCardDetailsUpdateOne) SetNillableNumber(s *string) *DebitCardDetailsUpdateOne {
	if s != nil {
		dcduo.SetNumber(*s)
	}
	return dcduo
}

// SetUsersID sets the "users" edge to the Users entity by ID.
func (dcduo *DebitCardDetailsUpdateOne) SetUsersID(id int) *DebitCardDetailsUpdateOne {
	dcduo.mutation.SetUsersID(id)
	return dcduo
}

// SetNillableUsersID sets the "users" edge to the Users entity by ID if the given value is not nil.
func (dcduo *DebitCardDetailsUpdateOne) SetNillableUsersID(id *int) *DebitCardDetailsUpdateOne {
	if id != nil {
		dcduo = dcduo.SetUsersID(*id)
	}
	return dcduo
}

// SetUsers sets the "users" edge to the Users entity.
func (dcduo *DebitCardDetailsUpdateOne) SetUsers(u *Users) *DebitCardDetailsUpdateOne {
	return dcduo.SetUsersID(u.ID)
}

// SetDebitCardsID sets the "debit_cards" edge to the DebitCards entity by ID.
func (dcduo *DebitCardDetailsUpdateOne) SetDebitCardsID(id int) *DebitCardDetailsUpdateOne {
	dcduo.mutation.SetDebitCardsID(id)
	return dcduo
}

// SetNillableDebitCardsID sets the "debit_cards" edge to the DebitCards entity by ID if the given value is not nil.
func (dcduo *DebitCardDetailsUpdateOne) SetNillableDebitCardsID(id *int) *DebitCardDetailsUpdateOne {
	if id != nil {
		dcduo = dcduo.SetDebitCardsID(*id)
	}
	return dcduo
}

// SetDebitCards sets the "debit_cards" edge to the DebitCards entity.
func (dcduo *DebitCardDetailsUpdateOne) SetDebitCards(d *DebitCards) *DebitCardDetailsUpdateOne {
	return dcduo.SetDebitCardsID(d.ID)
}

// Mutation returns the DebitCardDetailsMutation object of the builder.
func (dcduo *DebitCardDetailsUpdateOne) Mutation() *DebitCardDetailsMutation {
	return dcduo.mutation
}

// ClearUsers clears the "users" edge to the Users entity.
func (dcduo *DebitCardDetailsUpdateOne) ClearUsers() *DebitCardDetailsUpdateOne {
	dcduo.mutation.ClearUsers()
	return dcduo
}

// ClearDebitCards clears the "debit_cards" edge to the DebitCards entity.
func (dcduo *DebitCardDetailsUpdateOne) ClearDebitCards() *DebitCardDetailsUpdateOne {
	dcduo.mutation.ClearDebitCards()
	return dcduo
}

// Where appends a list predicates to the DebitCardDetailsUpdate builder.
func (dcduo *DebitCardDetailsUpdateOne) Where(ps ...predicate.DebitCardDetails) *DebitCardDetailsUpdateOne {
	dcduo.mutation.Where(ps...)
	return dcduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dcduo *DebitCardDetailsUpdateOne) Select(field string, fields ...string) *DebitCardDetailsUpdateOne {
	dcduo.fields = append([]string{field}, fields...)
	return dcduo
}

// Save executes the query and returns the updated DebitCardDetails entity.
func (dcduo *DebitCardDetailsUpdateOne) Save(ctx context.Context) (*DebitCardDetails, error) {
	return withHooks(ctx, dcduo.sqlSave, dcduo.mutation, dcduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dcduo *DebitCardDetailsUpdateOne) SaveX(ctx context.Context) *DebitCardDetails {
	node, err := dcduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dcduo *DebitCardDetailsUpdateOne) Exec(ctx context.Context) error {
	_, err := dcduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcduo *DebitCardDetailsUpdateOne) ExecX(ctx context.Context) {
	if err := dcduo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (dcduo *DebitCardDetailsUpdateOne) sqlSave(ctx context.Context) (_node *DebitCardDetails, err error) {
	_spec := sqlgraph.NewUpdateSpec(debitcarddetails.Table, debitcarddetails.Columns, sqlgraph.NewFieldSpec(debitcarddetails.FieldID, field.TypeInt))
	id, ok := dcduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DebitCardDetails.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := dcduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, debitcarddetails.FieldID)
		for _, f := range fields {
			if !debitcarddetails.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != debitcarddetails.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dcduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dcduo.mutation.Issuer(); ok {
		_spec.SetField(debitcarddetails.FieldIssuer, field.TypeString, value)
	}
	if value, ok := dcduo.mutation.Number(); ok {
		_spec.SetField(debitcarddetails.FieldNumber, field.TypeString, value)
	}
	if dcduo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   debitcarddetails.UsersTable,
			Columns: []string{debitcarddetails.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dcduo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   debitcarddetails.UsersTable,
			Columns: []string{debitcarddetails.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dcduo.mutation.DebitCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   debitcarddetails.DebitCardsTable,
			Columns: []string{debitcarddetails.DebitCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(debitcards.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dcduo.mutation.DebitCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   debitcarddetails.DebitCardsTable,
			Columns: []string{debitcarddetails.DebitCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(debitcards.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DebitCardDetails{config: dcduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dcduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{debitcarddetails.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	dcduo.mutation.done = true
	return _node, nil
}
