// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/debitcarddesign"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/predicate"
)

// DebitCardDesignDelete is the builder for deleting a DebitCardDesign entity.
type DebitCardDesignDelete struct {
	config
	hooks    []Hook
	mutation *DebitCardDesignMutation
}

// Where appends a list predicates to the DebitCardDesignDelete builder.
func (dcdd *DebitCardDesignDelete) Where(ps ...predicate.DebitCardDesign) *DebitCardDesignDelete {
	dcdd.mutation.Where(ps...)
	return dcdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dcdd *DebitCardDesignDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dcdd.sqlExec, dcdd.mutation, dcdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dcdd *DebitCardDesignDelete) ExecX(ctx context.Context) int {
	n, err := dcdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dcdd *DebitCardDesignDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(debitcarddesign.Table, sqlgraph.NewFieldSpec(debitcarddesign.FieldID, field.TypeInt))
	if ps := dcdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dcdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dcdd.mutation.done = true
	return affected, err
}

// DebitCardDesignDeleteOne is the builder for deleting a single DebitCardDesign entity.
type DebitCardDesignDeleteOne struct {
	dcdd *DebitCardDesignDelete
}

// Where appends a list predicates to the DebitCardDesignDelete builder.
func (dcddo *DebitCardDesignDeleteOne) Where(ps ...predicate.DebitCardDesign) *DebitCardDesignDeleteOne {
	dcddo.dcdd.mutation.Where(ps...)
	return dcddo
}

// Exec executes the deletion query.
func (dcddo *DebitCardDesignDeleteOne) Exec(ctx context.Context) error {
	n, err := dcddo.dcdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{debitcarddesign.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dcddo *DebitCardDesignDeleteOne) ExecX(ctx context.Context) {
	if err := dcddo.Exec(ctx); err != nil {
		panic(err)
	}
}
