// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/transactions"
	"github.com/mnsv1511/kasikorn-line-assignment/ent/users"
)

// TransactionsCreate is the builder for creating a Transactions entity.
type TransactionsCreate struct {
	config
	mutation *TransactionsMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (tc *TransactionsCreate) SetUserID(i int) *TransactionsCreate {
	tc.mutation.SetUserID(i)
	return tc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (tc *TransactionsCreate) SetNillableUserID(i *int) *TransactionsCreate {
	if i != nil {
		tc.SetUserID(*i)
	}
	return tc
}

// SetName sets the "name" field.
func (tc *TransactionsCreate) SetName(s string) *TransactionsCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetImage sets the "image" field.
func (tc *TransactionsCreate) SetImage(s string) *TransactionsCreate {
	tc.mutation.SetImage(s)
	return tc
}

// SetIsBank sets the "isBank" field.
func (tc *TransactionsCreate) SetIsBank(b bool) *TransactionsCreate {
	tc.mutation.SetIsBank(b)
	return tc
}

// SetUsersID sets the "users" edge to the Users entity by ID.
func (tc *TransactionsCreate) SetUsersID(id int) *TransactionsCreate {
	tc.mutation.SetUsersID(id)
	return tc
}

// SetNillableUsersID sets the "users" edge to the Users entity by ID if the given value is not nil.
func (tc *TransactionsCreate) SetNillableUsersID(id *int) *TransactionsCreate {
	if id != nil {
		tc = tc.SetUsersID(*id)
	}
	return tc
}

// SetUsers sets the "users" edge to the Users entity.
func (tc *TransactionsCreate) SetUsers(u *Users) *TransactionsCreate {
	return tc.SetUsersID(u.ID)
}

// Mutation returns the TransactionsMutation object of the builder.
func (tc *TransactionsCreate) Mutation() *TransactionsMutation {
	return tc.mutation
}

// Save creates the Transactions in the database.
func (tc *TransactionsCreate) Save(ctx context.Context) (*Transactions, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TransactionsCreate) SaveX(ctx context.Context) *Transactions {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TransactionsCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TransactionsCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TransactionsCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Transactions.name"`)}
	}
	if _, ok := tc.mutation.Image(); !ok {
		return &ValidationError{Name: "image", err: errors.New(`ent: missing required field "Transactions.image"`)}
	}
	if _, ok := tc.mutation.IsBank(); !ok {
		return &ValidationError{Name: "isBank", err: errors.New(`ent: missing required field "Transactions.isBank"`)}
	}
	return nil
}

func (tc *TransactionsCreate) sqlSave(ctx context.Context) (*Transactions, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TransactionsCreate) createSpec() (*Transactions, *sqlgraph.CreateSpec) {
	var (
		_node = &Transactions{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(transactions.Table, sqlgraph.NewFieldSpec(transactions.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(transactions.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Image(); ok {
		_spec.SetField(transactions.FieldImage, field.TypeString, value)
		_node.Image = value
	}
	if value, ok := tc.mutation.IsBank(); ok {
		_spec.SetField(transactions.FieldIsBank, field.TypeBool, value)
		_node.IsBank = value
	}
	if nodes := tc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactions.UsersTable,
			Columns: []string{transactions.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TransactionsCreateBulk is the builder for creating many Transactions entities in bulk.
type TransactionsCreateBulk struct {
	config
	err      error
	builders []*TransactionsCreate
}

// Save creates the Transactions entities in the database.
func (tcb *TransactionsCreateBulk) Save(ctx context.Context) ([]*Transactions, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Transactions, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransactionsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TransactionsCreateBulk) SaveX(ctx context.Context) []*Transactions {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TransactionsCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TransactionsCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
