// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccountBalances is the predicate function for accountbalances builders.
type AccountBalances func(*sql.Selector)

// AccountDetails is the predicate function for accountdetails builders.
type AccountDetails func(*sql.Selector)

// AccountFlags is the predicate function for accountflags builders.
type AccountFlags func(*sql.Selector)

// Accounts is the predicate function for accounts builders.
type Accounts func(*sql.Selector)

// Banners is the predicate function for banners builders.
type Banners func(*sql.Selector)

// DebitCardDesign is the predicate function for debitcarddesign builders.
type DebitCardDesign func(*sql.Selector)

// DebitCardDetails is the predicate function for debitcarddetails builders.
type DebitCardDetails func(*sql.Selector)

// DebitCardStatus is the predicate function for debitcardstatus builders.
type DebitCardStatus func(*sql.Selector)

// DebitCards is the predicate function for debitcards builders.
type DebitCards func(*sql.Selector)

// Transactions is the predicate function for transactions builders.
type Transactions func(*sql.Selector)

// UserGreetings is the predicate function for usergreetings builders.
type UserGreetings func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
